### ISSUE TITLE
After an http call $scope.events is not getting updated

### ISSUE THREAD

**Issue by Naveenbc** [Russian60/flex-calendar#12]

**Comment by VincentPuget** [comment]
This is fixed. Checkout last commit.

**Comment by Naveenbc** [comment]
After Change month function $scope.events is not working..

**Comment by VincentPuget** [comment]
Did you use $scope.apply ?
This test code works, even after change month : 
(I use a setTimeout to simulate an async server response.)

``` javascript
setTimeout(function()
{
  console.log("timeout");
  $scope.$apply(function()
  {
    $scope.options.disabledDates = [
        "2015-06-22",
        "2015-06-23",
        "2015-06-24",
        "2015-07-27",
        "2015-08-13",
        "2015-08-15",
        "2015-08-16",
        "2015-08-17",
        "2015-08-18"
    ];
    $scope.events = [
      {foo: "bar", date: "2015-09-17"},
      {foo: "bar", date: "2015-09-18"},
      {foo: "bar", date: "2015-09-19"},
      {foo: "bar", date: "2015-09-20"},
      {foo: "bar", date: "2015-10-18"},
      {foo: "bar", date: "2015-10-14"},
      {foo: "bar", date: "2015-10-13"},
      {foo: "bar", date: "2015-10-12"},
      {foo: "bar", date: "2015-10-11"}
    ];
  });

  console.log("timeout");
}, 5000);
```

**Comment by Naveenbc** [comment]
Sorry to disturb you again. No its not working. In change month function I added $scope.$apply it didn't work. Below is my code piece
Thanks for the response.
changeMonth: function(month) {

```
            ActivitiesService.getMonthlyActivities(monthStartDate.getTime()).then(function(activities){
                for(var i=0; i<activities.length; i++){
                    activities[i].date = new Date(activities[i].endTime);
                    event.push(activities[i]);
                }

                 $scope.$apply(function(){
                $scope.events = event;
                 });


            });
        }
```

**Comment by VincentPuget** [comment]
$scope.events use ISO format (YYYY-MM-DD) date string 

``` javascript
$scope.events = [{foo: "bar", date: "2015-09-02"}];
```

Format your `new Date(activities[i].endTime);`

In changeMonth method, you don't need to call $apply

``` javascript
changeMonth: function(month, year) {
    console.log("changeMonth", month, year);
    $scope.events = [
      {foo: "bar", date: "2015-10-03"},
      {foo: "bar", date: "2015-09-03"},
      {foo: "bar", date: "2015-08-03"}
    ];
}
```

this example works on my project.

**Comment by Naveenbc** [comment]
No Bro, it might be problem with my flexcalendar.js. $scope.events is not calling it's watch method itself in changeMonth function. Can you kindly share the link of latest flexcalendar.js.

**Comment by VincentPuget** [comment]
The master branch is up to date. Can you make an update of your flex-calendar source code ? 
`bower install flex-calendar --save`

Have you tried to replace your changeMonth function by this  ?

``` javascript
changeMonth: function(month, year) {
    console.log("changeMonth", month, year);
    $scope.events = [
      {foo: "bar", date: "2015-10-03"},
      {foo: "bar", date: "2015-09-03"},
      {foo: "bar", date: "2015-08-03"}
    ];
}
```

Have you javascript error in your dev console ?

**Comment by Naveenbc** [comment]
Yes, I tried replacing and it worked but after ActivitiesService call its not working. After ActivitiesService call even if hard code to your dates it's not working.

**Comment by VincentPuget** [comment]
Your ActivitiesService.getMonthlyActivities() is a promise. Are you sur that is resolved ? You don't have second argument in your .then().

Promise are asynchronous, you will may need $apply in your success callback.

**Comment by Naveenbc** [comment]
Yeah promises are asynchronous but how can I have a promise to return two arguments? A promise can send only one result, since it sends result through return statement.

**Comment by VincentPuget** [comment]
The then() method returns a Promise. It takes two arguments, both are callback functions for the success and failure cases of the Promise.

``` javascript
p.then(
  function(response) {
  // Promise Success
  console.log(response);
  }, 
  function(err) {
  // Promise Error
  console.log(err);
  }
);
```

**Comment by Naveenbc** [comment]
I am really very sorry local variable event was declared in controller level, it has to be changeMonth method level. now its working. And second argument error function is optional.

Thank you very much.

**Comment by VincentPuget** [comment]
Your welcome!
