### ISSUE TITLE
not working for ios and safari ( NaN )

### ISSUE THREAD

**Issue by nadeemkhan** [Russian60/flex-calendar#15]
please take a look attached screenshot.
![screen shot 2015-08-28 at 11 04 51 am](https://cloud.githubusercontent.com/assets/1510017/9539831/056c5b48-4d75-11e5-8889-406db56009c3.png)

**Comment by VincentPuget** [comment]
Hi,
I think this Codepen example was not updated with the last committed feature.
Download source code, follow the readme instructions and make your own project. It will be working. (I don't have any trouble with Safari and Ios)

**Comment by nadeemkhan** [comment]
great thanks for reply now its working everywhere.
