### ISSUE TITLE
Small erro in tutorial

### ISSUE THREAD

**Issue by ghost** [Russian60/flex-calendar#25]
Change:" Inject  'flex-calendar' and ..."
To:        " Inject 'flexcalendar' and ..."

 The  name correct of module. :D

**Comment by Loksly** [comment]
There's also a typo at README.md file:

`<script type="text/javascript" src="bower_components/angular-translate/angular-translate.min.js.js"></script>`

note it the double .js.js extension

**Comment by Loksly** [comment]
in fact none of the bower references is right. They should be:

```
<link rel="stylesheet" href="bower_components/flex-calendar/dist/flex-calendar.css">
<script type="text/javascript" src="bower_components/angular-translate/angular-translate.min.js"></script>
<script type="text/javascript" src="bower_components/flex-calendar/dist/flex-calendar.js"></script>  
```
