### ISSUE TITLE
Uncaught SyntaxError: Octal literals are not allowed in strict mode.

### ISSUE THREAD

**Issue by ninoCookies** [Russian60/flex-calendar#9]
If i add $scope.options to my Controller (controller attached to calendar view) i get the following error:
Uncaught SyntaxError: Octal literals are not allowed in strict mode. 
I know its because i'm using 'use strict';  at the top of my .js file but i was wondering is this due to folowing var's :  
defaultDate: new Date(2015, 06, 26),
minDate: new Date(2015, 06, 12),
maxDate: new Date(2015, 12, 31),

Is it possible to somehow rewrite this so it will work within 'use strict' rules?

Thank you for the great job with flex-calendar.

**Comment by VincentPuget** [comment]
Hi,
You can now use strict mode with flex-calendar.
Checkout the new source code (last commit) and use the ISO Format to passed your dates in your controller. (see README.md)
